name: academy
description: Menai Muttineers Pre-Flyball Academy - Android and Web V1.2.1
publish_to: 'none'
version: 1.2.2+5

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  crypto: ^3.0.6
  url_launcher: ^6.3.2
  youtube_player_iframe: ^6.0.2
  audioplayers: ^6.8.1
  confetti: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/trophy_chime.wav
